### ISSUE TITLE
Test issues in feed forward neural network

### ISSUE THREAD

**Issue by JustinNie** [yunjey/pytorch-tutorial#144]
In feedforward_neural_network, it builds `test_loader` with batch size which is same as training. But if we set the batch size of test to `len(test_dataset)`, the test process will be much faster.

**Comment by yunjey** [comment]
@JustinNie If you have enough gpu memory, you can speed up the testing procedure by using a larger batch_size. However, for more complex examples than feedforward_neural_network, testing with a large batch_size requires huge amounts of memory. Since not all users have enough memory, and also for consistency with other examples, I keep the tutorial code as it is now.
