### ISSUE TITLE
[Image Captioning] states in lstm()

### ISSUE THREAD

**Issue by RangoHU** [yunjey/pytorch-tutorial#22]
Hello,

I have a quick question on calling of the lstm() in model.py.

In the training step, you simply run lstm layer as: "**hiddens, _ = self.lstm(packed)**", without assigning the states. 

Differently, in the sampling step, you send the features of EncoderRNN to the lstm layer as: "**hiddens, states = self.lstm(inputs, states)**".

I wonder that why we send the state parameters in sampling step. Because it seems to me that the returned states are not used in sample() function, can we just do "hiddens, _ = self.lstm(inputs)"?

Thanks.

**Comment by yunjey** [comment]
### Training phase
If we don't assign hidden state, `nn.LSTM` assigns zero state as initial state in default. It is desirable to set the initial state value of `nn.LSTM` to zero.

### Test phase
In `hiddens, states = self.lstm(inputs, states)`, you should note that returned `states` are used for the next time step. If you do not assign the states such as `self.lstm(inputs)`, it assigns zero states internally and it performs wrong operation. 

In test phase, the shape of `inputs` is <b>(batch_size, 1, embed_size)</b> so that only 1 time step forward propagation is performed when `self.lstm(inputs, states)` is called.

**Comment by RangoHU** [comment]
It makes much sense to me. Thanks for the answer!
