### ISSUE TITLE
Tutorial 09: Issues converting encoder and decoder models to CPUs pytorch 0.1.11

### ISSUE THREAD

**Issue by lgraesser** [yunjey/pytorch-tutorial#27]
Thanks for a fantastic tutorial. Really clear and easy to follow!

I'd like to run the pretrained models on a CPU, and am trying to convert the models as follows:

encoder.load_state_dict(torch.load(args.encoder_path, map_location=lambda storage, loc: storage))
decoder.load_state_dict(torch.load(args.decoder_path, map_location=lambda storage, loc: storage))

I also tried:
    encoder = torch.load(args.encoder_path, map_location=lambda storage, loc: storage)
    decoder = torch.load(args.decoder_path, map_location=lambda storage, loc: storage)

as advised by the pytorch developers (https://discuss.pytorch.org/t/on-a-cpu-device-how-to-load-checkpoint-saved-on-gpu-device/349/8)

Based on the discussions it seems that it might be a pytorch versioning issue. Could you let me know what version of pytorch you used to train and save the models? Or if it's something else, would really appreciate any guidance in getting it fixed.

Many thanks!

**Comment by yunjey** [comment]
This is PyTorch version issue. You can see [here](https://discuss.pytorch.org/t/params-requires-grad-false-has-elevated-memory-usage-in-v0-1-11/1625). You can solve this problem if you use Python 3.5 instead of 2.7. Also, you can fix this problem by replacing 'requires_grad' to 'volatiles'. 

This issue is automatically resolved when a new version of PyTorch is released.

**Comment by lgraesser** [comment]
Thanks a lot for letting me know the version. Also, I'll try switching to python 3.5 and see if that helps.
