### ISSUE TITLE
[DCGAN] Deep Convolutional Generative Adversarial Network

### ISSUE THREAD

**Issue by FYXX** [yunjey/pytorch-tutorial#34]
When I follow the tutorials to train this network, I can not get effective image results.  What should I do？？

I made the following modifications

# Save the sampled images
 fake_images = fake_images.view(fake_images.size(0), 3, 32, 32)
 torchvision.utils.save_image(fake_images.data, './sample/fake_samples_%d.png'

![qq 20170520170512](https://cloud.githubusercontent.com/assets/12612743/26274562/fde389d6-3d7e-11e7-89cc-6264022487dd.jpg)

**Comment by yunjey** [comment]
@FYXX  Perhaps this happened because torchvision was updated. To fix this issue, you should change the code [here](https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/11%20-%20Deep%20Convolutional%20Generative%20Adversarial%20Network/main.py#L129) to denormalize the image ((fake_image.data + 1) / 2). Then, the value range in the tensor will be between 0 and 1.

I will fixed this issue soon.

**Comment by yunjey** [comment]
@FYXX Even i changed the code, the result is not good. I will check this soon.

**Comment by FYXX** [comment]
Thank you very much and look forward to your good news

**Comment by FYXX** [comment]
This is the result of my training 100 epochs, and the result is not very good
![image](https://cloud.githubusercontent.com/assets/12612743/26448847/e9b8690c-4181-11e7-914b-d76f5033f84b.png)

**Comment by yunjey** [comment]
@FYXX I fixed the code of the DCGAN that works on CelebA dataset. Try the updated code.

**Comment by FYXX** [comment]
Thank you ~
